version: '3.8'

services:
  v1_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./home-helper-database/v1:/docker-entrypoint-initdb.d
      - ./volume/data/home_helper/v1:/var/lib/postgresql/data

  job_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${JOB_DB_USER}
      POSTGRES_PASSWORD: ${JOB_DB_PASS}
      POSTGRES_DB: ${JOB_DB_NAME}
    ports:
      - ${JOB_DB_PORT}:5432
    volumes:
      - ./home-helper-database/job_db:/docker-entrypoint-initdb.d
      - ./volume/data/home_helper/job:/var/lib/postgresql/data

volumes:
  v1_db:
    driver: local
  job_db:
    driver: local
