version: '3.8'

services:
  v1_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./home-helper-database/v1:/docker-entrypoint-initdb.d
      - ./volume/data/home_helper/v1:/var/lib/postgresql/data

  work_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${WORK_DB_USER}
      POSTGRES_PASSWORD: ${WORK_DB_PASS}
      POSTGRES_DB: ${WORK_DB_NAME}
    ports:
      - ${WORK_DB_PORT}:5432
    volumes:
      - ./home-helper-database/work_db:/docker-entrypoint-initdb.d
      - ./volume/data/home_helper/work:/var/lib/postgresql/data

volumes:
  v1_db:
    driver: local
  work_db:
    driver: local
