/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface ConvIdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.conv_id
     *
     * @mbg.generated
     */
    int deleteByExample(ConvIdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.conv_id
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.conv_id
     *
     * @mbg.generated
     */
    int insert(ConvId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.conv_id
     *
     * @mbg.generated
     */
    int insertSelective(ConvId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.conv_id
     *
     * @mbg.generated
     */
    ConvId selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.conv_id
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConvId record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.conv_id
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConvId record);
}