/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1GroupApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group_application
     *
     * @mbg.generated
     */
    int deleteByExample(DbV1GroupApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group_application
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String groupApplicationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group_application
     *
     * @mbg.generated
     */
    int insert(DbV1GroupApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group_application
     *
     * @mbg.generated
     */
    int insertSelective(DbV1GroupApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group_application
     *
     * @mbg.generated
     */
    DbV1GroupApplication selectByPrimaryKey(String groupApplicationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group_application
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1GroupApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group_application
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1GroupApplication record);
}