/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1CreditCardSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.credit_card_summary
     *
     * @mbg.generated
     */
    int deleteByExample(DbV1CreditCardSummaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.credit_card_summary
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.credit_card_summary
     *
     * @mbg.generated
     */
    int insert(DbV1CreditCardSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.credit_card_summary
     *
     * @mbg.generated
     */
    int insertSelective(DbV1CreditCardSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.credit_card_summary
     *
     * @mbg.generated
     */
    DbV1CreditCardSummary selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.credit_card_summary
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1CreditCardSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.credit_card_summary
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1CreditCardSummary record);
}