/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import java.math.BigDecimal;
import java.time.LocalDate;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@AllArgsConstructor
@Builder
public class DbV1CreditCardSummary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.credit_card_summary.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.credit_card_summary.credit_card
     *
     * @mbg.generated
     */
    private String creditCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.credit_card_summary.withdrawal_date
     *
     * @mbg.generated
     */
    private LocalDate withdrawalDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.credit_card_summary.account_id
     *
     * @mbg.generated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.credit_card_summary.total_amount
     *
     * @mbg.generated
     */
    private BigDecimal totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.credit_card_summary.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.credit_card_summary.group_id
     *
     * @mbg.generated
     */
    private String groupId;
}