/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import java.time.LocalDateTime;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@AllArgsConstructor
@Builder
public class DbV1HelperPointExchangedAchievement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.help_point_exchanged_achievement.help_point_exchanged_achievement_id
     *
     * @mbg.generated
     */
    private String helpPointExchangedAchievementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.help_point_exchanged_achievement.helper_kid_id
     *
     * @mbg.generated
     */
    private String helperKidId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.help_point_exchanged_achievement.exchange_item_id
     *
     * @mbg.generated
     */
    private String exchangeItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.help_point_exchanged_achievement.exchange_count
     *
     * @mbg.generated
     */
    private Integer exchangeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.help_point_exchanged_achievement.exchange_total_point
     *
     * @mbg.generated
     */
    private Integer exchangeTotalPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.help_point_exchanged_achievement.exchanged_datetime
     *
     * @mbg.generated
     */
    private LocalDateTime exchangedDatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.help_point_exchanged_achievement.group_id
     *
     * @mbg.generated
     */
    private String groupId;
}