/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1ImportFileHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.import_file_history
     *
     * @mbg.generated
     */
    int deleteByExample(DbV1ImportFileHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.import_file_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.import_file_history
     *
     * @mbg.generated
     */
    int insert(DbV1ImportFileHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.import_file_history
     *
     * @mbg.generated
     */
    int insertSelective(DbV1ImportFileHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.import_file_history
     *
     * @mbg.generated
     */
    DbV1ImportFileHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.import_file_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1ImportFileHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.import_file_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1ImportFileHistory record);
}