/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1TransferCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transfer_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transfer_category
     *
     * @mbg.generated
     */
    int insert(DbV1TransferCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transfer_category
     *
     * @mbg.generated
     */
    int insertSelective(DbV1TransferCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transfer_category
     *
     * @mbg.generated
     */
    DbV1TransferCategory selectByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transfer_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1TransferCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.transfer_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1TransferCategory record);
}