/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.account
     *
     * @mbg.generated
     */
    int insert(DbV1Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.account
     *
     * @mbg.generated
     */
    int insertSelective(DbV1Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.account
     *
     * @mbg.generated
     */
    DbV1Account selectByPrimaryKey(String accountId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1Account record);
}