/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1AffiliationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String affiliationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    int insert(DbV1Affiliation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    int insertSelective(DbV1Affiliation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    DbV1Affiliation selectByPrimaryKey(String affiliationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1Affiliation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1Affiliation record);
}