/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@AllArgsConstructor
@Builder
public class DbV1Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account.account_id
     *
     * @mbg.generated
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account.account_name
     *
     * @mbg.generated
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account.valid_flag
     *
     * @mbg.generated
     */
    private Boolean validFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account.display_order
     *
     * @mbg.generated
     */
    private Integer displayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.account.group_id
     *
     * @mbg.generated
     */
    private String groupId;
}