/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1ExchangeItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.exchange_item
     *
     * @mbg.generated
     */
    int deleteByExample(DbV1ExchangeItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.exchange_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String exchangeItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.exchange_item
     *
     * @mbg.generated
     */
    int insert(DbV1ExchangeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.exchange_item
     *
     * @mbg.generated
     */
    int insertSelective(DbV1ExchangeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.exchange_item
     *
     * @mbg.generated
     */
    DbV1ExchangeItem selectByPrimaryKey(String exchangeItemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.exchange_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1ExchangeItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.exchange_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1ExchangeItem record);
}