/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import java.util.ArrayList;
import java.util.List;

public class DbV1GenreExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    public DbV1GenreExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andGenreIdIsNull() {
            addCriterion("genre_id is null");
            return (Criteria) this;
        }

        public Criteria andGenreIdIsNotNull() {
            addCriterion("genre_id is not null");
            return (Criteria) this;
        }

        public Criteria andGenreIdEqualTo(String value) {
            addCriterion("genre_id =", value, "genreId");
            return (Criteria) this;
        }

        public Criteria andGenreIdNotEqualTo(String value) {
            addCriterion("genre_id <>", value, "genreId");
            return (Criteria) this;
        }

        public Criteria andGenreIdGreaterThan(String value) {
            addCriterion("genre_id >", value, "genreId");
            return (Criteria) this;
        }

        public Criteria andGenreIdGreaterThanOrEqualTo(String value) {
            addCriterion("genre_id >=", value, "genreId");
            return (Criteria) this;
        }

        public Criteria andGenreIdLessThan(String value) {
            addCriterion("genre_id <", value, "genreId");
            return (Criteria) this;
        }

        public Criteria andGenreIdLessThanOrEqualTo(String value) {
            addCriterion("genre_id <=", value, "genreId");
            return (Criteria) this;
        }

        public Criteria andGenreIdLike(String value) {
            addCriterion("genre_id like", value, "genreId");
            return (Criteria) this;
        }

        public Criteria andGenreIdNotLike(String value) {
            addCriterion("genre_id not like", value, "genreId");
            return (Criteria) this;
        }

        public Criteria andGenreIdIn(List<String> values) {
            addCriterion("genre_id in", values, "genreId");
            return (Criteria) this;
        }

        public Criteria andGenreIdNotIn(List<String> values) {
            addCriterion("genre_id not in", values, "genreId");
            return (Criteria) this;
        }

        public Criteria andGenreIdBetween(String value1, String value2) {
            addCriterion("genre_id between", value1, value2, "genreId");
            return (Criteria) this;
        }

        public Criteria andGenreIdNotBetween(String value1, String value2) {
            addCriterion("genre_id not between", value1, value2, "genreId");
            return (Criteria) this;
        }

        public Criteria andGenreNameIsNull() {
            addCriterion("genre_name is null");
            return (Criteria) this;
        }

        public Criteria andGenreNameIsNotNull() {
            addCriterion("genre_name is not null");
            return (Criteria) this;
        }

        public Criteria andGenreNameEqualTo(String value) {
            addCriterion("genre_name =", value, "genreName");
            return (Criteria) this;
        }

        public Criteria andGenreNameNotEqualTo(String value) {
            addCriterion("genre_name <>", value, "genreName");
            return (Criteria) this;
        }

        public Criteria andGenreNameGreaterThan(String value) {
            addCriterion("genre_name >", value, "genreName");
            return (Criteria) this;
        }

        public Criteria andGenreNameGreaterThanOrEqualTo(String value) {
            addCriterion("genre_name >=", value, "genreName");
            return (Criteria) this;
        }

        public Criteria andGenreNameLessThan(String value) {
            addCriterion("genre_name <", value, "genreName");
            return (Criteria) this;
        }

        public Criteria andGenreNameLessThanOrEqualTo(String value) {
            addCriterion("genre_name <=", value, "genreName");
            return (Criteria) this;
        }

        public Criteria andGenreNameLike(String value) {
            addCriterion("genre_name like", value, "genreName");
            return (Criteria) this;
        }

        public Criteria andGenreNameNotLike(String value) {
            addCriterion("genre_name not like", value, "genreName");
            return (Criteria) this;
        }

        public Criteria andGenreNameIn(List<String> values) {
            addCriterion("genre_name in", values, "genreName");
            return (Criteria) this;
        }

        public Criteria andGenreNameNotIn(List<String> values) {
            addCriterion("genre_name not in", values, "genreName");
            return (Criteria) this;
        }

        public Criteria andGenreNameBetween(String value1, String value2) {
            addCriterion("genre_name between", value1, value2, "genreName");
            return (Criteria) this;
        }

        public Criteria andGenreNameNotBetween(String value1, String value2) {
            addCriterion("genre_name not between", value1, value2, "genreName");
            return (Criteria) this;
        }

        public Criteria andGenreTypeIsNull() {
            addCriterion("genre_type is null");
            return (Criteria) this;
        }

        public Criteria andGenreTypeIsNotNull() {
            addCriterion("genre_type is not null");
            return (Criteria) this;
        }

        public Criteria andGenreTypeEqualTo(String value) {
            addCriterion("genre_type =", value, "genreType");
            return (Criteria) this;
        }

        public Criteria andGenreTypeNotEqualTo(String value) {
            addCriterion("genre_type <>", value, "genreType");
            return (Criteria) this;
        }

        public Criteria andGenreTypeGreaterThan(String value) {
            addCriterion("genre_type >", value, "genreType");
            return (Criteria) this;
        }

        public Criteria andGenreTypeGreaterThanOrEqualTo(String value) {
            addCriterion("genre_type >=", value, "genreType");
            return (Criteria) this;
        }

        public Criteria andGenreTypeLessThan(String value) {
            addCriterion("genre_type <", value, "genreType");
            return (Criteria) this;
        }

        public Criteria andGenreTypeLessThanOrEqualTo(String value) {
            addCriterion("genre_type <=", value, "genreType");
            return (Criteria) this;
        }

        public Criteria andGenreTypeLike(String value) {
            addCriterion("genre_type like", value, "genreType");
            return (Criteria) this;
        }

        public Criteria andGenreTypeNotLike(String value) {
            addCriterion("genre_type not like", value, "genreType");
            return (Criteria) this;
        }

        public Criteria andGenreTypeIn(List<String> values) {
            addCriterion("genre_type in", values, "genreType");
            return (Criteria) this;
        }

        public Criteria andGenreTypeNotIn(List<String> values) {
            addCriterion("genre_type not in", values, "genreType");
            return (Criteria) this;
        }

        public Criteria andGenreTypeBetween(String value1, String value2) {
            addCriterion("genre_type between", value1, value2, "genreType");
            return (Criteria) this;
        }

        public Criteria andGenreTypeNotBetween(String value1, String value2) {
            addCriterion("genre_type not between", value1, value2, "genreType");
            return (Criteria) this;
        }

        public Criteria andIocomeTypeIsNull() {
            addCriterion("iocome_type is null");
            return (Criteria) this;
        }

        public Criteria andIocomeTypeIsNotNull() {
            addCriterion("iocome_type is not null");
            return (Criteria) this;
        }

        public Criteria andIocomeTypeEqualTo(String value) {
            addCriterion("iocome_type =", value, "iocomeType");
            return (Criteria) this;
        }

        public Criteria andIocomeTypeNotEqualTo(String value) {
            addCriterion("iocome_type <>", value, "iocomeType");
            return (Criteria) this;
        }

        public Criteria andIocomeTypeGreaterThan(String value) {
            addCriterion("iocome_type >", value, "iocomeType");
            return (Criteria) this;
        }

        public Criteria andIocomeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("iocome_type >=", value, "iocomeType");
            return (Criteria) this;
        }

        public Criteria andIocomeTypeLessThan(String value) {
            addCriterion("iocome_type <", value, "iocomeType");
            return (Criteria) this;
        }

        public Criteria andIocomeTypeLessThanOrEqualTo(String value) {
            addCriterion("iocome_type <=", value, "iocomeType");
            return (Criteria) this;
        }

        public Criteria andIocomeTypeLike(String value) {
            addCriterion("iocome_type like", value, "iocomeType");
            return (Criteria) this;
        }

        public Criteria andIocomeTypeNotLike(String value) {
            addCriterion("iocome_type not like", value, "iocomeType");
            return (Criteria) this;
        }

        public Criteria andIocomeTypeIn(List<String> values) {
            addCriterion("iocome_type in", values, "iocomeType");
            return (Criteria) this;
        }

        public Criteria andIocomeTypeNotIn(List<String> values) {
            addCriterion("iocome_type not in", values, "iocomeType");
            return (Criteria) this;
        }

        public Criteria andIocomeTypeBetween(String value1, String value2) {
            addCriterion("iocome_type between", value1, value2, "iocomeType");
            return (Criteria) this;
        }

        public Criteria andIocomeTypeNotBetween(String value1, String value2) {
            addCriterion("iocome_type not between", value1, value2, "iocomeType");
            return (Criteria) this;
        }

        public Criteria andValidFlagIsNull() {
            addCriterion("valid_flag is null");
            return (Criteria) this;
        }

        public Criteria andValidFlagIsNotNull() {
            addCriterion("valid_flag is not null");
            return (Criteria) this;
        }

        public Criteria andValidFlagEqualTo(Boolean value) {
            addCriterion("valid_flag =", value, "validFlag");
            return (Criteria) this;
        }

        public Criteria andValidFlagNotEqualTo(Boolean value) {
            addCriterion("valid_flag <>", value, "validFlag");
            return (Criteria) this;
        }

        public Criteria andValidFlagGreaterThan(Boolean value) {
            addCriterion("valid_flag >", value, "validFlag");
            return (Criteria) this;
        }

        public Criteria andValidFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("valid_flag >=", value, "validFlag");
            return (Criteria) this;
        }

        public Criteria andValidFlagLessThan(Boolean value) {
            addCriterion("valid_flag <", value, "validFlag");
            return (Criteria) this;
        }

        public Criteria andValidFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("valid_flag <=", value, "validFlag");
            return (Criteria) this;
        }

        public Criteria andValidFlagIn(List<Boolean> values) {
            addCriterion("valid_flag in", values, "validFlag");
            return (Criteria) this;
        }

        public Criteria andValidFlagNotIn(List<Boolean> values) {
            addCriterion("valid_flag not in", values, "validFlag");
            return (Criteria) this;
        }

        public Criteria andValidFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("valid_flag between", value1, value2, "validFlag");
            return (Criteria) this;
        }

        public Criteria andValidFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("valid_flag not between", value1, value2, "validFlag");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderIsNull() {
            addCriterion("display_order is null");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderIsNotNull() {
            addCriterion("display_order is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderEqualTo(Integer value) {
            addCriterion("display_order =", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNotEqualTo(Integer value) {
            addCriterion("display_order <>", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderGreaterThan(Integer value) {
            addCriterion("display_order >", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("display_order >=", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderLessThan(Integer value) {
            addCriterion("display_order <", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderLessThanOrEqualTo(Integer value) {
            addCriterion("display_order <=", value, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderIn(List<Integer> values) {
            addCriterion("display_order in", values, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNotIn(List<Integer> values) {
            addCriterion("display_order not in", values, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderBetween(Integer value1, Integer value2) {
            addCriterion("display_order between", value1, value2, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andDisplayOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("display_order not between", value1, value2, "displayOrder");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(String value) {
            addCriterion("group_id =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(String value) {
            addCriterion("group_id <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(String value) {
            addCriterion("group_id >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("group_id >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(String value) {
            addCriterion("group_id <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(String value) {
            addCriterion("group_id <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLike(String value) {
            addCriterion("group_id like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotLike(String value) {
            addCriterion("group_id not like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<String> values) {
            addCriterion("group_id in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<String> values) {
            addCriterion("group_id not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(String value1, String value2) {
            addCriterion("group_id between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(String value1, String value2) {
            addCriterion("group_id not between", value1, value2, "groupId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.genre
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}