/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1HelperPointEarnedDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_point_earned_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String helpPointEarnedDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_point_earned_detail
     *
     * @mbg.generated
     */
    int insert(DbV1HelperPointEarnedDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_point_earned_detail
     *
     * @mbg.generated
     */
    int insertSelective(DbV1HelperPointEarnedDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_point_earned_detail
     *
     * @mbg.generated
     */
    DbV1HelperPointEarnedDetail selectByPrimaryKey(String helpPointEarnedDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_point_earned_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1HelperPointEarnedDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_point_earned_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1HelperPointEarnedDetail record);
}