/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1GenreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String genreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    int insert(DbV1Genre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    int insertSelective(DbV1Genre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    DbV1Genre selectByPrimaryKey(String genreId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1Genre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.genre
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1Genre record);
}