/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1CreditCardDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.credit_card_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.credit_card_detail
     *
     * @mbg.generated
     */
    int insert(DbV1CreditCardDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.credit_card_detail
     *
     * @mbg.generated
     */
    int insertSelective(DbV1CreditCardDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.credit_card_detail
     *
     * @mbg.generated
     */
    DbV1CreditCardDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.credit_card_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1CreditCardDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.credit_card_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1CreditCardDetail record);
}