/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@AllArgsConstructor
@Builder
public class DbV1HelperKidParent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.helper_kid_parent.helper_kid_parent_id
     *
     * @mbg.generated
     */
    private String helperKidParentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.helper_kid_parent.helper_kid_id
     *
     * @mbg.generated
     */
    private String helperKidId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.helper_kid_parent.parent_user_id
     *
     * @mbg.generated
     */
    private String parentUserId;
}