/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1DailyDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.daily_detail
     *
     * @mbg.generated
     */
    int deleteByExample(DbV1DailyDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.daily_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.daily_detail
     *
     * @mbg.generated
     */
    int insert(DbV1DailyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.daily_detail
     *
     * @mbg.generated
     */
    int insertSelective(DbV1DailyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.daily_detail
     *
     * @mbg.generated
     */
    DbV1DailyDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.daily_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1DailyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.daily_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1DailyDetail record);
}