/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1SummaryCategoryByGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.summary_category_by_group
     *
     * @mbg.generated
     */
    int deleteByExample(DbV1SummaryCategoryByGroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.summary_category_by_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.summary_category_by_group
     *
     * @mbg.generated
     */
    int insert(DbV1SummaryCategoryByGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.summary_category_by_group
     *
     * @mbg.generated
     */
    int insertSelective(DbV1SummaryCategoryByGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.summary_category_by_group
     *
     * @mbg.generated
     */
    DbV1SummaryCategoryByGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.summary_category_by_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1SummaryCategoryByGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.summary_category_by_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1SummaryCategoryByGroup record);
}