/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import java.util.ArrayList;
import java.util.List;

public class DbV1AffiliationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    public DbV1AffiliationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAffiliationIdIsNull() {
            addCriterion("affiliation_id is null");
            return (Criteria) this;
        }

        public Criteria andAffiliationIdIsNotNull() {
            addCriterion("affiliation_id is not null");
            return (Criteria) this;
        }

        public Criteria andAffiliationIdEqualTo(String value) {
            addCriterion("affiliation_id =", value, "affiliationId");
            return (Criteria) this;
        }

        public Criteria andAffiliationIdNotEqualTo(String value) {
            addCriterion("affiliation_id <>", value, "affiliationId");
            return (Criteria) this;
        }

        public Criteria andAffiliationIdGreaterThan(String value) {
            addCriterion("affiliation_id >", value, "affiliationId");
            return (Criteria) this;
        }

        public Criteria andAffiliationIdGreaterThanOrEqualTo(String value) {
            addCriterion("affiliation_id >=", value, "affiliationId");
            return (Criteria) this;
        }

        public Criteria andAffiliationIdLessThan(String value) {
            addCriterion("affiliation_id <", value, "affiliationId");
            return (Criteria) this;
        }

        public Criteria andAffiliationIdLessThanOrEqualTo(String value) {
            addCriterion("affiliation_id <=", value, "affiliationId");
            return (Criteria) this;
        }

        public Criteria andAffiliationIdLike(String value) {
            addCriterion("affiliation_id like", value, "affiliationId");
            return (Criteria) this;
        }

        public Criteria andAffiliationIdNotLike(String value) {
            addCriterion("affiliation_id not like", value, "affiliationId");
            return (Criteria) this;
        }

        public Criteria andAffiliationIdIn(List<String> values) {
            addCriterion("affiliation_id in", values, "affiliationId");
            return (Criteria) this;
        }

        public Criteria andAffiliationIdNotIn(List<String> values) {
            addCriterion("affiliation_id not in", values, "affiliationId");
            return (Criteria) this;
        }

        public Criteria andAffiliationIdBetween(String value1, String value2) {
            addCriterion("affiliation_id between", value1, value2, "affiliationId");
            return (Criteria) this;
        }

        public Criteria andAffiliationIdNotBetween(String value1, String value2) {
            addCriterion("affiliation_id not between", value1, value2, "affiliationId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(String value) {
            addCriterion("group_id =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(String value) {
            addCriterion("group_id <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(String value) {
            addCriterion("group_id >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("group_id >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(String value) {
            addCriterion("group_id <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(String value) {
            addCriterion("group_id <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLike(String value) {
            addCriterion("group_id like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotLike(String value) {
            addCriterion("group_id not like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<String> values) {
            addCriterion("group_id in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<String> values) {
            addCriterion("group_id not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(String value1, String value2) {
            addCriterion("group_id between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(String value1, String value2) {
            addCriterion("group_id not between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupRoleIdIsNull() {
            addCriterion("group_role_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupRoleIdIsNotNull() {
            addCriterion("group_role_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupRoleIdEqualTo(String value) {
            addCriterion("group_role_id =", value, "groupRoleId");
            return (Criteria) this;
        }

        public Criteria andGroupRoleIdNotEqualTo(String value) {
            addCriterion("group_role_id <>", value, "groupRoleId");
            return (Criteria) this;
        }

        public Criteria andGroupRoleIdGreaterThan(String value) {
            addCriterion("group_role_id >", value, "groupRoleId");
            return (Criteria) this;
        }

        public Criteria andGroupRoleIdGreaterThanOrEqualTo(String value) {
            addCriterion("group_role_id >=", value, "groupRoleId");
            return (Criteria) this;
        }

        public Criteria andGroupRoleIdLessThan(String value) {
            addCriterion("group_role_id <", value, "groupRoleId");
            return (Criteria) this;
        }

        public Criteria andGroupRoleIdLessThanOrEqualTo(String value) {
            addCriterion("group_role_id <=", value, "groupRoleId");
            return (Criteria) this;
        }

        public Criteria andGroupRoleIdLike(String value) {
            addCriterion("group_role_id like", value, "groupRoleId");
            return (Criteria) this;
        }

        public Criteria andGroupRoleIdNotLike(String value) {
            addCriterion("group_role_id not like", value, "groupRoleId");
            return (Criteria) this;
        }

        public Criteria andGroupRoleIdIn(List<String> values) {
            addCriterion("group_role_id in", values, "groupRoleId");
            return (Criteria) this;
        }

        public Criteria andGroupRoleIdNotIn(List<String> values) {
            addCriterion("group_role_id not in", values, "groupRoleId");
            return (Criteria) this;
        }

        public Criteria andGroupRoleIdBetween(String value1, String value2) {
            addCriterion("group_role_id between", value1, value2, "groupRoleId");
            return (Criteria) this;
        }

        public Criteria andGroupRoleIdNotBetween(String value1, String value2) {
            addCriterion("group_role_id not between", value1, value2, "groupRoleId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.affiliation
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}