/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1ApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.application
     *
     * @mbg.generated
     */
    int deleteByExample(DbV1ApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.application
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String applicationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.application
     *
     * @mbg.generated
     */
    int insert(DbV1Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.application
     *
     * @mbg.generated
     */
    int insertSelective(DbV1Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.application
     *
     * @mbg.generated
     */
    DbV1Application selectByPrimaryKey(String applicationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.application
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.application
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1Application record);
}