/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@AllArgsConstructor
@Builder
public class DbV1Genre {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.genre.genre_id
     *
     * @mbg.generated
     */
    private String genreId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.genre.genre_name
     *
     * @mbg.generated
     */
    private String genreName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.genre.genre_type
     *
     * @mbg.generated
     */
    private String genreType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.genre.iocome_type
     *
     * @mbg.generated
     */
    private String iocomeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.genre.valid_flag
     *
     * @mbg.generated
     */
    private Boolean validFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.genre.display_order
     *
     * @mbg.generated
     */
    private Integer displayOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.genre.group_id
     *
     * @mbg.generated
     */
    private String groupId;
}