/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1GroupRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group_role
     *
     * @mbg.generated
     */
    int deleteByExample(DbV1GroupRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String groupRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group_role
     *
     * @mbg.generated
     */
    int insert(DbV1GroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group_role
     *
     * @mbg.generated
     */
    int insertSelective(DbV1GroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group_role
     *
     * @mbg.generated
     */
    DbV1GroupRole selectByPrimaryKey(String groupRoleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1GroupRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1GroupRole record);
}