/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV1DepositCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.deposit_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.deposit_category
     *
     * @mbg.generated
     */
    int insert(DbV1DepositCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.deposit_category
     *
     * @mbg.generated
     */
    int insertSelective(DbV1DepositCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.deposit_category
     *
     * @mbg.generated
     */
    DbV1DepositCategory selectByPrimaryKey(String categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.deposit_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV1DepositCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.deposit_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV1DepositCategory record);
}