/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import java.util.ArrayList;
import java.util.List;

public class DbV1HelperKidExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    public DbV1HelperKidExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHelperKidIdIsNull() {
            addCriterion("helper_kid_id is null");
            return (Criteria) this;
        }

        public Criteria andHelperKidIdIsNotNull() {
            addCriterion("helper_kid_id is not null");
            return (Criteria) this;
        }

        public Criteria andHelperKidIdEqualTo(String value) {
            addCriterion("helper_kid_id =", value, "helperKidId");
            return (Criteria) this;
        }

        public Criteria andHelperKidIdNotEqualTo(String value) {
            addCriterion("helper_kid_id <>", value, "helperKidId");
            return (Criteria) this;
        }

        public Criteria andHelperKidIdGreaterThan(String value) {
            addCriterion("helper_kid_id >", value, "helperKidId");
            return (Criteria) this;
        }

        public Criteria andHelperKidIdGreaterThanOrEqualTo(String value) {
            addCriterion("helper_kid_id >=", value, "helperKidId");
            return (Criteria) this;
        }

        public Criteria andHelperKidIdLessThan(String value) {
            addCriterion("helper_kid_id <", value, "helperKidId");
            return (Criteria) this;
        }

        public Criteria andHelperKidIdLessThanOrEqualTo(String value) {
            addCriterion("helper_kid_id <=", value, "helperKidId");
            return (Criteria) this;
        }

        public Criteria andHelperKidIdLike(String value) {
            addCriterion("helper_kid_id like", value, "helperKidId");
            return (Criteria) this;
        }

        public Criteria andHelperKidIdNotLike(String value) {
            addCriterion("helper_kid_id not like", value, "helperKidId");
            return (Criteria) this;
        }

        public Criteria andHelperKidIdIn(List<String> values) {
            addCriterion("helper_kid_id in", values, "helperKidId");
            return (Criteria) this;
        }

        public Criteria andHelperKidIdNotIn(List<String> values) {
            addCriterion("helper_kid_id not in", values, "helperKidId");
            return (Criteria) this;
        }

        public Criteria andHelperKidIdBetween(String value1, String value2) {
            addCriterion("helper_kid_id between", value1, value2, "helperKidId");
            return (Criteria) this;
        }

        public Criteria andHelperKidIdNotBetween(String value1, String value2) {
            addCriterion("helper_kid_id not between", value1, value2, "helperKidId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameSuffixIsNull() {
            addCriterion("name_suffix is null");
            return (Criteria) this;
        }

        public Criteria andNameSuffixIsNotNull() {
            addCriterion("name_suffix is not null");
            return (Criteria) this;
        }

        public Criteria andNameSuffixEqualTo(String value) {
            addCriterion("name_suffix =", value, "nameSuffix");
            return (Criteria) this;
        }

        public Criteria andNameSuffixNotEqualTo(String value) {
            addCriterion("name_suffix <>", value, "nameSuffix");
            return (Criteria) this;
        }

        public Criteria andNameSuffixGreaterThan(String value) {
            addCriterion("name_suffix >", value, "nameSuffix");
            return (Criteria) this;
        }

        public Criteria andNameSuffixGreaterThanOrEqualTo(String value) {
            addCriterion("name_suffix >=", value, "nameSuffix");
            return (Criteria) this;
        }

        public Criteria andNameSuffixLessThan(String value) {
            addCriterion("name_suffix <", value, "nameSuffix");
            return (Criteria) this;
        }

        public Criteria andNameSuffixLessThanOrEqualTo(String value) {
            addCriterion("name_suffix <=", value, "nameSuffix");
            return (Criteria) this;
        }

        public Criteria andNameSuffixLike(String value) {
            addCriterion("name_suffix like", value, "nameSuffix");
            return (Criteria) this;
        }

        public Criteria andNameSuffixNotLike(String value) {
            addCriterion("name_suffix not like", value, "nameSuffix");
            return (Criteria) this;
        }

        public Criteria andNameSuffixIn(List<String> values) {
            addCriterion("name_suffix in", values, "nameSuffix");
            return (Criteria) this;
        }

        public Criteria andNameSuffixNotIn(List<String> values) {
            addCriterion("name_suffix not in", values, "nameSuffix");
            return (Criteria) this;
        }

        public Criteria andNameSuffixBetween(String value1, String value2) {
            addCriterion("name_suffix between", value1, value2, "nameSuffix");
            return (Criteria) this;
        }

        public Criteria andNameSuffixNotBetween(String value1, String value2) {
            addCriterion("name_suffix not between", value1, value2, "nameSuffix");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNull() {
            addCriterion("group_id is null");
            return (Criteria) this;
        }

        public Criteria andGroupIdIsNotNull() {
            addCriterion("group_id is not null");
            return (Criteria) this;
        }

        public Criteria andGroupIdEqualTo(String value) {
            addCriterion("group_id =", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotEqualTo(String value) {
            addCriterion("group_id <>", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThan(String value) {
            addCriterion("group_id >", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("group_id >=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThan(String value) {
            addCriterion("group_id <", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLessThanOrEqualTo(String value) {
            addCriterion("group_id <=", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdLike(String value) {
            addCriterion("group_id like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotLike(String value) {
            addCriterion("group_id not like", value, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdIn(List<String> values) {
            addCriterion("group_id in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotIn(List<String> values) {
            addCriterion("group_id not in", values, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdBetween(String value1, String value2) {
            addCriterion("group_id between", value1, value2, "groupId");
            return (Criteria) this;
        }

        public Criteria andGroupIdNotBetween(String value1, String value2) {
            addCriterion("group_id not between", value1, value2, "groupId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table helper_kids.helper_kid
     *
     * @mbg.generated
     */
    public static class Criterion {
        private final String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private final String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}