/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v1.table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@AllArgsConstructor
@Builder
public class DbV1Application {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.application.application_id
     *
     * @mbg.generated
     */
    private String applicationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.application.application
     *
     * @mbg.generated
     */
    private String application;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.application.valid_flag
     *
     * @mbg.generated
     */
    private Boolean validFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column public.application.top_url
     *
     * @mbg.generated
     */
    private String topUrl;
}