spring:
  job-datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://${JOB_DB_HOST}:${JOB_DB_PORT}/${JOB_DB_NAME}
    username: ${JOB_DB_USER}
    password: ${JOB_DB_PASS}
    driver-class-name: org.postgresql.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true