spring:
  # JobRepositoryおよび退避用のテーブルを保持します。
  datasource:
    url: jdbc:postgresql://${WORK_DB_HOST}:${WORK_DB_PORT}/${WORK_DB_NAME}
    username: ${WORK_DB_USER}
    password: ${WORK_DB_PASS}
    driver-class-name: org.postgresql.Driver
  # version1 のデータベースを保持します。
  v1-datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org:
      springframework: INFO
    home:
      helper:
        batch:
          persistence:
            DEBUG