/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@AllArgsConstructor
@Builder
public class DbV2DepositCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household.deposit_category.category_id
     *
     * @mbg.generated
     */
    private String categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household.deposit_category.group_id
     *
     * @mbg.generated
     */
    private String groupId;
}