/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2AffiliationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2AffiliationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    int insert(DbV2Affiliation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    int insertSelective(DbV2Affiliation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    DbV2Affiliation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2Affiliation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.affiliation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2Affiliation record);
}