/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2CategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.category
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2CategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.category
     *
     * @mbg.generated
     */
    int insert(DbV2Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.category
     *
     * @mbg.generated
     */
    int insertSelective(DbV2Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.category
     *
     * @mbg.generated
     */
    DbV2Category selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2Category record);
}