/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2SummaryCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.summary_category
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2SummaryCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.summary_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.summary_category
     *
     * @mbg.generated
     */
    int insert(DbV2SummaryCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.summary_category
     *
     * @mbg.generated
     */
    int insertSelective(DbV2SummaryCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.summary_category
     *
     * @mbg.generated
     */
    DbV2SummaryCategory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.summary_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2SummaryCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.summary_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2SummaryCategory record);
}