/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@AllArgsConstructor
@Builder
public class DbV2HelpPointEarnedDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.help_point_earned_detail.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.help_point_earned_detail.achievement_id
     *
     * @mbg.generated
     */
    private String achievementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.help_point_earned_detail.help_item_id
     *
     * @mbg.generated
     */
    private String helpItemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.help_point_earned_detail.count
     *
     * @mbg.generated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.help_point_earned_detail.total_point
     *
     * @mbg.generated
     */
    private Integer totalPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column helper_kids.help_point_earned_detail.group_id
     *
     * @mbg.generated
     */
    private String groupId;
}