/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import home.helper.batch.persistence.database.v2.table.DbV2Account;
import home.helper.batch.persistence.database.v2.table.DbV2AccountExample;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2AccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.account
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2AccountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.account
     *
     * @mbg.generated
     */
    int insert(DbV2Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.account
     *
     * @mbg.generated
     */
    int insertSelective(DbV2Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.account
     *
     * @mbg.generated
     */
    DbV2Account selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2Account record);
}