/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2ImportFileHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.import_file_history
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2ImportFileHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.import_file_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.import_file_history
     *
     * @mbg.generated
     */
    int insert(DbV2ImportFileHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.import_file_history
     *
     * @mbg.generated
     */
    int insertSelective(DbV2ImportFileHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.import_file_history
     *
     * @mbg.generated
     */
    DbV2ImportFileHistory selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.import_file_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2ImportFileHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.import_file_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2ImportFileHistory record);
}