/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2DailyDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.daily_detail
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2DailyDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.daily_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.daily_detail
     *
     * @mbg.generated
     */
    int insert(DbV2DailyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.daily_detail
     *
     * @mbg.generated
     */
    int insertSelective(DbV2DailyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.daily_detail
     *
     * @mbg.generated
     */
    DbV2DailyDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.daily_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2DailyDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.daily_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2DailyDetail record);
}