/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2GroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2GroupExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group
     *
     * @mbg.generated
     */
    int insert(DbV2Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group
     *
     * @mbg.generated
     */
    int insertSelective(DbV2Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group
     *
     * @mbg.generated
     */
    DbV2Group selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2Group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2Group record);
}