/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@AllArgsConstructor
@Builder
public class DbV2Account {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household.account.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household.account.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household.account.valid_flag
     *
     * @mbg.generated
     */
    private Boolean validFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household.account.display_order
     *
     * @mbg.generated
     */
    private Integer displayOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column household.account.group_id
     *
     * @mbg.generated
     */
    private String groupId;
}