/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2TransferCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.transfer_category
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2TransferCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.transfer_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.transfer_category
     *
     * @mbg.generated
     */
    int insert(DbV2TransferCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.transfer_category
     *
     * @mbg.generated
     */
    int insertSelective(DbV2TransferCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.transfer_category
     *
     * @mbg.generated
     */
    DbV2TransferCategory selectByPrimaryKey(String groupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.transfer_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2TransferCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.transfer_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2TransferCategory record);
}