/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2ApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.application
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2ApplicationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.application
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.application
     *
     * @mbg.generated
     */
    int insert(DbV2Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.application
     *
     * @mbg.generated
     */
    int insertSelective(DbV2Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.application
     *
     * @mbg.generated
     */
    DbV2Application selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.application
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2Application record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table public.application
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2Application record);
}