/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2GenreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.genre
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2GenreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.genre
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.genre
     *
     * @mbg.generated
     */
    int insert(DbV2Genre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.genre
     *
     * @mbg.generated
     */
    int insertSelective(DbV2Genre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.genre
     *
     * @mbg.generated
     */
    DbV2Genre selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.genre
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2Genre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.genre
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2Genre record);
}