/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2HelpItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_item
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2HelpItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_item
     *
     * @mbg.generated
     */
    int insert(DbV2HelpItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_item
     *
     * @mbg.generated
     */
    int insertSelective(DbV2HelpItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_item
     *
     * @mbg.generated
     */
    DbV2HelpItem selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2HelpItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2HelpItem record);
}