/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2DepositCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.deposit_category
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2DepositCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.deposit_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.deposit_category
     *
     * @mbg.generated
     */
    int insert(DbV2DepositCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.deposit_category
     *
     * @mbg.generated
     */
    int insertSelective(DbV2DepositCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.deposit_category
     *
     * @mbg.generated
     */
    DbV2DepositCategory selectByPrimaryKey(String categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.deposit_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2DepositCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.deposit_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2DepositCategory record);
}