/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2HelperKidParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid_parent
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2HelperKidParentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid_parent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid_parent
     *
     * @mbg.generated
     */
    int insert(DbV2HelperKidParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid_parent
     *
     * @mbg.generated
     */
    int insertSelective(DbV2HelperKidParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid_parent
     *
     * @mbg.generated
     */
    DbV2HelperKidParent selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid_parent
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2HelperKidParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.helper_kid_parent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2HelperKidParent record);
}