/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2CreditCardDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.credit_card_detail
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2CreditCardDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.credit_card_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.credit_card_detail
     *
     * @mbg.generated
     */
    int insert(DbV2CreditCardDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.credit_card_detail
     *
     * @mbg.generated
     */
    int insertSelective(DbV2CreditCardDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.credit_card_detail
     *
     * @mbg.generated
     */
    DbV2CreditCardDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.credit_card_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2CreditCardDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table household.credit_card_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2CreditCardDetail record);
}