/*
 * Copyright (c) 2023 Ryo-Kgym.
 */

package home.helper.batch.persistence.database.v2.table;

import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DbV2HelpPointEarnedDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_point_earned_detail
     *
     * @mbg.generated
     */
    int deleteByExample(DbV2HelpPointEarnedDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_point_earned_detail
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_point_earned_detail
     *
     * @mbg.generated
     */
    int insert(DbV2HelpPointEarnedDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_point_earned_detail
     *
     * @mbg.generated
     */
    int insertSelective(DbV2HelpPointEarnedDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_point_earned_detail
     *
     * @mbg.generated
     */
    DbV2HelpPointEarnedDetail selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_point_earned_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(DbV2HelpPointEarnedDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table helper_kids.help_point_earned_detail
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(DbV2HelpPointEarnedDetail record);
}